ifneq ($(KERNELRELEASE),)
KHOOK_DIR	:= $(shell dirname $(shell realpath --relative-to=$(src) $(lastword $(MAKEFILE_LIST))))
KHOOK_GOALS	:= $(KHOOK_DIR)/khook/engine.o
ifeq ($(ARCH),x86)
KHOOK_GOALS	+= $(KHOOK_DIR)/khook/x86/hook.o $(KHOOK_DIR)/khook/x86/stub.o
else
$(error "ARCH is NOT supported")
endif
KHOOK_CCFLAGS	:= -I$(src)/$(KHOOK_DIR) $(call cc-option,-fcf-protection=none)
KHOOK_LDFLAGS	:= -T$(src)/$(KHOOK_DIR)/khook/engine.lds
endif
